[[GAP_pkg_juliainterface]]
arch = "aarch64"
git-tree-sha1 = "52d5514b26d96a93a19910af8a37d41a49c40cea"
julia_version = "1.10.0"
os = "macos"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "5e3f8048779819e2852f5fda6d6d6cae2a16b19ed8ab1be552c49eda187f7318"
    url = "https://github.com/lgoettgens/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.160000.0+0/GAP_pkg_juliainterface.v0.160000.0.aarch64-apple-darwin-julia_version+1.10.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "aarch64"
git-tree-sha1 = "8e1caa035c9bab4418d3ce361ea99eb0c2cf193f"
julia_version = "1.11.1"
os = "macos"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "ff6cc8792e80e8f900ebbf6e95b6cf88fedd3e0e470373468416d9d4f35ccbeb"
    url = "https://github.com/lgoettgens/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.160000.0+0/GAP_pkg_juliainterface.v0.160000.0.aarch64-apple-darwin-julia_version+1.11.1.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "aarch64"
git-tree-sha1 = "ee3616e1fde171bed644306185339257da9171fe"
julia_version = "1.12.0"
os = "macos"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "b861bfeff22ff688a0d5a9120be02c114826128fb457736ffb38b9cd592eff7a"
    url = "https://github.com/lgoettgens/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.160000.0+0/GAP_pkg_juliainterface.v0.160000.0.aarch64-apple-darwin-julia_version+1.12.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "aarch64"
git-tree-sha1 = "ff862c1b0dcfe561185bb107bebdd813a022d102"
julia_version = "1.13.0"
os = "macos"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "31179d9a99c46c0381b297f09911cb484fc92d04f5729f2bb77b545c6a85947b"
    url = "https://github.com/lgoettgens/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.160000.0+0/GAP_pkg_juliainterface.v0.160000.0.aarch64-apple-darwin-julia_version+1.13.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "aarch64"
git-tree-sha1 = "162636580e5dcccef61de99e17f93b28cca65933"
julia_version = "1.10.0"
libc = "glibc"
os = "linux"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "d47087f89af0a4d54e459dbc9072ddf6b0eb44bdedf647e0d59019e4bc8ca0bc"
    url = "https://github.com/lgoettgens/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.160000.0+0/GAP_pkg_juliainterface.v0.160000.0.aarch64-linux-gnu-julia_version+1.10.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "aarch64"
git-tree-sha1 = "2337d56c964d58015d613779ca6ece10e1842a3b"
julia_version = "1.11.1"
libc = "glibc"
os = "linux"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "076cded3ddae8e90696d6040f33c637f08856297df0cbd25779ef887bf7dd264"
    url = "https://github.com/lgoettgens/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.160000.0+0/GAP_pkg_juliainterface.v0.160000.0.aarch64-linux-gnu-julia_version+1.11.1.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "aarch64"
git-tree-sha1 = "0e91889c495087a15b08b37f4fcf44a83b28cac7"
julia_version = "1.12.0"
libc = "glibc"
os = "linux"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "e2bcc214f1f5e6a51d7fa8045bc809267ce0a2d5e07eff5f4b88e9dfba876ae5"
    url = "https://github.com/lgoettgens/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.160000.0+0/GAP_pkg_juliainterface.v0.160000.0.aarch64-linux-gnu-julia_version+1.12.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "aarch64"
git-tree-sha1 = "1e0e11968ecbbc07dffb0744717967ced6129468"
julia_version = "1.13.0"
libc = "glibc"
os = "linux"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "acddc110427eacef60b75cb78c324412a71b6d8d09fac425353af7f19aa515c7"
    url = "https://github.com/lgoettgens/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.160000.0+0/GAP_pkg_juliainterface.v0.160000.0.aarch64-linux-gnu-julia_version+1.13.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "aarch64"
git-tree-sha1 = "db6d61cde7b5c458161623bb471bdc745fd37a6f"
julia_version = "1.10.0"
libc = "musl"
os = "linux"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "537f17d8c9e39bbb4bc3d968e6c3d1ba32c7a721c1d6b4131f6df498924fc929"
    url = "https://github.com/lgoettgens/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.160000.0+0/GAP_pkg_juliainterface.v0.160000.0.aarch64-linux-musl-julia_version+1.10.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "aarch64"
git-tree-sha1 = "49194204f90f0c7b4fcdaefcaa37dcaf2d10ab68"
julia_version = "1.11.1"
libc = "musl"
os = "linux"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "c9fc34a1da6d35750822863f86c2e3c95ad91ea03eb82b2057e77f16e7e2e705"
    url = "https://github.com/lgoettgens/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.160000.0+0/GAP_pkg_juliainterface.v0.160000.0.aarch64-linux-musl-julia_version+1.11.1.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "aarch64"
git-tree-sha1 = "94d42c6eb1a58cae648bc8d186d35ef3ae7c8c9e"
julia_version = "1.12.0"
libc = "musl"
os = "linux"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "f7a575817d1e90d167fa9079a0979a7444e141d943d4013287ad12e3f21bab64"
    url = "https://github.com/lgoettgens/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.160000.0+0/GAP_pkg_juliainterface.v0.160000.0.aarch64-linux-musl-julia_version+1.12.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "aarch64"
git-tree-sha1 = "5ede4262913005e7ccd85b7198718c2987965c16"
julia_version = "1.13.0"
libc = "musl"
os = "linux"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "f11e946d75e574f7069cd4614fcb2ea7cd1a581b673ebca87503fca0d33031ac"
    url = "https://github.com/lgoettgens/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.160000.0+0/GAP_pkg_juliainterface.v0.160000.0.aarch64-linux-musl-julia_version+1.13.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "aarch64"
git-tree-sha1 = "c2b70b21d95994bdd2b585f205deb42f8881c356"
julia_version = "1.12.0"
os = "freebsd"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "3e184261805a64830ff555bcd8b3a80a00f36bb1b9a3f14691e581fcd7f25bd4"
    url = "https://github.com/lgoettgens/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.160000.0+0/GAP_pkg_juliainterface.v0.160000.0.aarch64-unknown-freebsd-julia_version+1.12.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "aarch64"
git-tree-sha1 = "23d840dcea3aa494ee7d0333d9d744e0ca710cc4"
julia_version = "1.13.0"
os = "freebsd"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "b7da07afebc0b849f00f6137f4b54875bcd66d556f02396ccb2fe059036fd5bc"
    url = "https://github.com/lgoettgens/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.160000.0+0/GAP_pkg_juliainterface.v0.160000.0.aarch64-unknown-freebsd-julia_version+1.13.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "powerpc64le"
git-tree-sha1 = "aab8292ba3ac04ed58ba214fd6b184897ce00407"
julia_version = "1.10.0"
libc = "glibc"
os = "linux"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "873bd89bf36899f0c06c63c7f0475b4255840c5d767b6ed31d75d8f5eb1adaa4"
    url = "https://github.com/lgoettgens/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.160000.0+0/GAP_pkg_juliainterface.v0.160000.0.powerpc64le-linux-gnu-julia_version+1.10.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "powerpc64le"
git-tree-sha1 = "72ee086159544eb5247ea9ab712b9b8f70963736"
julia_version = "1.11.1"
libc = "glibc"
os = "linux"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "008cb013c3d31f7f07b70274e0f568be2db8062e97378b4f925d0580405581db"
    url = "https://github.com/lgoettgens/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.160000.0+0/GAP_pkg_juliainterface.v0.160000.0.powerpc64le-linux-gnu-julia_version+1.11.1.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "powerpc64le"
git-tree-sha1 = "5b1eb6b5b6a8235f5582228392b001b83dbd1f28"
julia_version = "1.12.0"
libc = "glibc"
os = "linux"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "ce9b19bdb9ece524706a46abe91079ac2704dd0e3c212b8d1d0bf2b17408fc32"
    url = "https://github.com/lgoettgens/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.160000.0+0/GAP_pkg_juliainterface.v0.160000.0.powerpc64le-linux-gnu-julia_version+1.12.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "powerpc64le"
git-tree-sha1 = "0abc079272ce3ef1d1fc8095ac5ecd89ce474792"
julia_version = "1.13.0"
libc = "glibc"
os = "linux"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "c6909d15a0aaaae6270cd181e40866a2c179770cb94c15004d78806810d9a67e"
    url = "https://github.com/lgoettgens/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.160000.0+0/GAP_pkg_juliainterface.v0.160000.0.powerpc64le-linux-gnu-julia_version+1.13.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "riscv64"
git-tree-sha1 = "d0a13b7ea038280cd4b51d6a280546bb889b8953"
julia_version = "1.13.0"
libc = "glibc"
os = "linux"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "b6e857c5496bf954d0b85f65405e2c0bde9f989073a9e55c2a18cbfc68c2084e"
    url = "https://github.com/lgoettgens/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.160000.0+0/GAP_pkg_juliainterface.v0.160000.0.riscv64-linux-gnu-julia_version+1.13.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "x86_64"
git-tree-sha1 = "1bc913922e2c45823343d6a5c83278b08e347459"
julia_version = "1.10.0"
os = "macos"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "08839554ac7dd18129bf48c4284317170e09695b3085d9de7f4946ceba7ebb90"
    url = "https://github.com/lgoettgens/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.160000.0+0/GAP_pkg_juliainterface.v0.160000.0.x86_64-apple-darwin-julia_version+1.10.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "x86_64"
git-tree-sha1 = "96da51806f4906f5d3784141d273f3a2fd02517a"
julia_version = "1.11.1"
os = "macos"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "5e0673bc6986e4d49c3769929b373889c3e9f669876af5229e862f6d98e40cbb"
    url = "https://github.com/lgoettgens/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.160000.0+0/GAP_pkg_juliainterface.v0.160000.0.x86_64-apple-darwin-julia_version+1.11.1.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "x86_64"
git-tree-sha1 = "b4e45a5c8ab9965e3ffd212afbe90cf175b3a4b9"
julia_version = "1.12.0"
os = "macos"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "7891706153cd30748cc7061d6f60bc56265fd6027a27802c43bfd4d88d67343d"
    url = "https://github.com/lgoettgens/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.160000.0+0/GAP_pkg_juliainterface.v0.160000.0.x86_64-apple-darwin-julia_version+1.12.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "x86_64"
git-tree-sha1 = "6d76bed7842df941dd85e1d643c5f40067bde6e9"
julia_version = "1.13.0"
os = "macos"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "edefc09d1f26ce14c10a31e303f06b7ff5ad14226bb51524c877a94082e611ca"
    url = "https://github.com/lgoettgens/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.160000.0+0/GAP_pkg_juliainterface.v0.160000.0.x86_64-apple-darwin-julia_version+1.13.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "x86_64"
git-tree-sha1 = "52ca810fa90895fd2fd6bd01b8c591f577f8ecea"
julia_version = "1.10.0"
libc = "glibc"
os = "linux"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "60e3d13faa3b68052c74adc603018c3715196a61083de38bd7e7c558b779a0ba"
    url = "https://github.com/lgoettgens/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.160000.0+0/GAP_pkg_juliainterface.v0.160000.0.x86_64-linux-gnu-julia_version+1.10.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "x86_64"
git-tree-sha1 = "4172ee61ceace68d5bfa72d49906109423a0dbd4"
julia_version = "1.11.1"
libc = "glibc"
os = "linux"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "9fdc6cf14981c387f25012c33f7d369585c0c4f679af6499b07bff35d4a91af2"
    url = "https://github.com/lgoettgens/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.160000.0+0/GAP_pkg_juliainterface.v0.160000.0.x86_64-linux-gnu-julia_version+1.11.1.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "x86_64"
git-tree-sha1 = "01f057f2da4977ab26f7cb1eff7826aa660f717a"
julia_version = "1.12.0"
libc = "glibc"
os = "linux"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "b149521c1cfdfd468de039e7e19120c9e13c85a3ec8114f60da097d880916a11"
    url = "https://github.com/lgoettgens/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.160000.0+0/GAP_pkg_juliainterface.v0.160000.0.x86_64-linux-gnu-julia_version+1.12.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "x86_64"
git-tree-sha1 = "747f29473efd318a5b0ad1f4a1dec5dfb89cb3b5"
julia_version = "1.13.0"
libc = "glibc"
os = "linux"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "7d4138f30ca82b9ed2ced1b1bbf087114e2ebd611b8f3cfa41bce5749f06d062"
    url = "https://github.com/lgoettgens/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.160000.0+0/GAP_pkg_juliainterface.v0.160000.0.x86_64-linux-gnu-julia_version+1.13.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "x86_64"
git-tree-sha1 = "a85f7c8d1d176dc14f18913a1922d7724b40dd8a"
julia_version = "1.10.0"
libc = "musl"
os = "linux"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "215adf6137646078ab5a3fd605394ff75faf60c9b4847a8bb43d14c98f7a6166"
    url = "https://github.com/lgoettgens/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.160000.0+0/GAP_pkg_juliainterface.v0.160000.0.x86_64-linux-musl-julia_version+1.10.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "x86_64"
git-tree-sha1 = "f4204846212c26fb808d98488792bb4b126c51ee"
julia_version = "1.11.1"
libc = "musl"
os = "linux"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "030261b313ef365cb38c692e9f800dce362e2e93e02b1aeb080a5ffdb9fadcd6"
    url = "https://github.com/lgoettgens/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.160000.0+0/GAP_pkg_juliainterface.v0.160000.0.x86_64-linux-musl-julia_version+1.11.1.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "x86_64"
git-tree-sha1 = "72f4688303541303096f90c501df631bd44a6a2b"
julia_version = "1.12.0"
libc = "musl"
os = "linux"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "5b368e1600b66581fde19d6c5db5dd7d5a6865399c702b1c8a8182605890450c"
    url = "https://github.com/lgoettgens/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.160000.0+0/GAP_pkg_juliainterface.v0.160000.0.x86_64-linux-musl-julia_version+1.12.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "x86_64"
git-tree-sha1 = "77a3121f6761d4207d3cae118130012cebee9163"
julia_version = "1.13.0"
libc = "musl"
os = "linux"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "af88cef4e01cde46a41eaa19a3bfb53e9b603c205e149f5940c346c6335b9a12"
    url = "https://github.com/lgoettgens/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.160000.0+0/GAP_pkg_juliainterface.v0.160000.0.x86_64-linux-musl-julia_version+1.13.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "x86_64"
git-tree-sha1 = "cbb07eef349f15875419318cba6c3a5a8a5d6e76"
julia_version = "1.10.0"
os = "freebsd"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "1758beb39f999b6738d15aee50182194c9681c9ca1e9c32ee0f91d600bbaed08"
    url = "https://github.com/lgoettgens/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.160000.0+0/GAP_pkg_juliainterface.v0.160000.0.x86_64-unknown-freebsd-julia_version+1.10.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "x86_64"
git-tree-sha1 = "9055a21328af4853820a97b47a87f6ba35ccf6e6"
julia_version = "1.11.1"
os = "freebsd"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "f1b235fe32f38bb97769190b6a20b947e3019badda6cdd5e0d69a5793d2fa4a9"
    url = "https://github.com/lgoettgens/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.160000.0+0/GAP_pkg_juliainterface.v0.160000.0.x86_64-unknown-freebsd-julia_version+1.11.1.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "x86_64"
git-tree-sha1 = "6bb077b0ed426b172d63de77d317b28bccc986ef"
julia_version = "1.12.0"
os = "freebsd"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "34a129ea76750c025b245722d38039d7f2fc47f5e0ffbaccde0952c86a540cdb"
    url = "https://github.com/lgoettgens/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.160000.0+0/GAP_pkg_juliainterface.v0.160000.0.x86_64-unknown-freebsd-julia_version+1.12.0.tar.gz"
[[GAP_pkg_juliainterface]]
arch = "x86_64"
git-tree-sha1 = "5a2eb4528da2358d0c9b4afc85ee85c837601110"
julia_version = "1.13.0"
os = "freebsd"

    [[GAP_pkg_juliainterface.download]]
    sha256 = "195c45074d7a1bc97a4e9a7423b7aab40725445c6a962e8899bb60dd95a87fd6"
    url = "https://github.com/lgoettgens/GAP_pkg_juliainterface_jll.jl/releases/download/GAP_pkg_juliainterface-v0.160000.0+0/GAP_pkg_juliainterface.v0.160000.0.x86_64-unknown-freebsd-julia_version+1.13.0.tar.gz"
